name: Learning GitHub Script

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueComment = await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🎉 You've created this issue comment using GitHub Script!!!"
            });

            const columnID = 12345678; // 👈 Aquí pon el ID real de la columna del proyecto

            await github.rest.projects.createCard({
              column_id: columnID,
              content_id: context.payload.issue.id,
              content_type: "Issue"
            });
